(begin
  (display (and 1 2))
  (newline)
  (display (or #f 3))
  (newline)
  (when #t
    (display 4)
    (newline))
  (unless #f
    (display 5)
    (newline))
  (display (cond ((zero? 1) 6) ((zero? 0) 7) (else 8)))
  (newline)
  (display (case 2 ((1) 9) ((2 3) 10) (else 11)))
  (newline)
  (display (do ((i 0 (+ i 1))
                (acc 0 (+ acc i)))
               ((zero? (- 4 i)) acc)))
  (newline)
  0)
