(write (map + '(1 2 3) '(4 5 6)))
(newline)
(write (map (lambda (x) (+ x 1)) '(1 2 3)))
(newline)
(for-each (lambda (x)
            (display x)
            (newline))
          '(7 8))
(write (memq 'b '(a b c)))
(newline)
(write (member '(2) '((1) (2) (3))))
(newline)
(write (assq 'b '((a . 1) (b . 2))))
(newline)
(write (assoc '(2) '(((1) . a) ((2) . b))))
(newline)
0
