(begin
  (write (list 1 2 3))
  (newline)
  (display (list? '(1 2 3)))
  (newline)
  (display (list? (cons 1 2)))
  (newline)
  (display (length (list 4 5 6)))
  (newline)
  (display (list-ref (list 7 8 9) 1))
  (newline)
  (write (list-tail (list 7 8 9) 1))
  (newline)
  (write (append (list 1 2) (list 3 4)))
  (newline)
  (display (not #f))
  (newline)
  (display (not (list 1)))
  (newline)
  0)
